### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by deadnameremoval** [MarSoft/upwork-wayland#1]
Hello there!

Is the code up-to-date? I have noticed that when Upwork tries to screenshot the output messages your code should be outputting are not (the idletime messages, however, keep working). 

Did Upwork change the way they get their screenshot or something in the script might be broken?

Any advice on that?

Thanks a lot!

**Comment by MarSoft** [comment]
Hello! Yes, the code is up-to-date, I did use it today with Upwork `5.6.10.13`.
Which window manager do you use?
I advise you to monitor the dbus traffic using `dbus-monitor` tool, it's very useful. Just run `dbus-monitor` in the terminal, optionally pipe its output to the text file by appending ` | tee history.txt`, and then wait for Upwork to try to make a screenshot.
You should notice `method call` line for destination `org.gnome.Shell.Screenshot` and path `/org/gnome/Shell/Screenshot`, and probably also a corresponding `method return` line.
That's where you can start debugging your issue.

**Comment by MarSoft** [comment]
If you find anything useful, please share here, so that we'll be able to pin down and fix the problem.

**Comment by deadnameremoval** [comment]
Hello, I apologize for taking so long!

Thanks a lot for the hint, @MarSoft 

I am running same Upwork version on `wayfire` (package `wayfire-git 0.7.2.r191.g9458f589-1` from the ArchLinux User Repository). I will follow your suggestion on using `dbus-monitor` next time I get back there (probably tomorrow), thanks a lot!

I have also noticed, recently, that `Upwork` is running over `XWayland`. I am wondering if this might be the problem, since it's also not getting the window titles properly on my work log. Are you also running it through `XWayland`? If not, where did you find instructions to run natively on wayland?

**Comment by deadnameremoval** [comment]
Hello again!

I have inspected the `dbus` messages time to time in the last week, and it seems to me that `Upwork` app isn't even trying to call the `org.gnome.Shell.Screenshot` over `dbus`. It seems to explain why your script outputs only the message about being requested the idle timer. They might have changed how they take screenshots, or at least it seems the case. It even screenshots with success for the first time (and then fails all the others).

Anyway, I think it's an issue at the `Upwork` app and not at your script, so I'll close this issue.

Thanks a lot for your response anyway!
